[package]
name = "matypst"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Esdras"]
license = "MIT"
description = "Caixas coloridas, ambientes matemáticos e código estilizado para Typst"
repository = "https://github.com/esdras/matypst"
keywords = ["tcolorbox", "theorem", "box", "math", "code"]
categories = ["components", "visualization"]
compiler = "0.14.0"
